- name: create dirs
  file:
    path: '{{ item }}'
    state: directory
    owner: root
    group: root
  with_items:
    - '{{ mariadb_conf.backup_dir }}'

- name: manage backup.sh
  template:
    src: templates/backup.sh
    dest: /usr/local/bin/mariadb_backup.sh
    owner: root
    group: root
    mode: 0755

- cron:
    name: 'mariadb backup'
    minute: '0'
    hour: '0'
    user: root
    job: '/bin/bash /usr/local/bin/mariadb_backup.sh'
